# Begin Project
project:
  type: tutorial-template
  # FYI: the tutorial-template project type is defined in the lmu-osc/tutorial-template extension
# End Project

# Begin Website
repo-url: https://github.com/lmu-osc/code-publishing
website:
  title: "Code Publishing Tutorial"
  page-footer:
    border: false
    center: © 2025 Florian Kohrt, Josephine Zerna, Christoph Scheffel, Felix Schönbrodt, Pat Callahan. Published by LMU Open Science Center. Licensed under CC BY-SA 4.0.

  navbar:
    right:
      - about.qmd
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/lmu-osc/code-publishing
          - text: Report a Bug
            href: https://github.com/lmu-osc/code-publishing/issues
      - icon: house-heart
        url: https://www.osc.lmu.de/

  sidebar:
    style: "docked"
    contents:
      - text: "Overview"
        href: index.qmd
      - intro.qmd
      - setup.qmd
      - copyright.qmd
      - data.qmd
      - code.qmd
      - choose-license.qmd
      - make-readme.qmd
      - archive.qmd
      - section: "In-depth material"
        contents:
          - href: in-depth-material/introduction-copyright.qmd
            text: "Introduction to Copyright and Licensing"
          - href: in-depth-material/copyright-conditions.qmd
            text: "Copyright Conditions"
          - href: in-depth-material/data-dic-generation.qmd
            text: "Automatic Generation of Data Dictionaries"
          - href: in-depth-material/licenses-continued.qmd
            text: "Licenses Continued"
          - href: in-depth-material/other-dependencies.qmd
            text: "Identify additional system dependencies for the README"
# End Website

# Begin Includes
include-in-header:
  - file: matomo-analytics.html
# End Includes

# Begin Format
# use only if needed. the default format for `tutorial-template` projects is tutorial-template-html+tutorial
format:
  tutorial-template-html+tutorial:
    fontsize: 13pt
    mermaid:
      theme: neutral
    css:
      - footer/footer-style.css
    include-after-body:
      - file: footer/footer.html
# End Format

# Begin Editor
editor: source
# End Editor

csl: apa.csl
bibliography: references.bib
lang: en-US
